[2022-12-13T00:00:26.444+0000] {processor.py:154} INFO - Started process (PID=1084) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:00:26.445+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:00:26.445+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:00:26.445+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:00:29.838+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:00:29.853+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 3.411 seconds
[2022-12-13T00:00:59.931+0000] {processor.py:154} INFO - Started process (PID=1145) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:00:59.932+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:00:59.933+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:00:59.933+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:01:06.178+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:01:06.192+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 6.267 seconds
[2022-12-13T00:01:36.424+0000] {processor.py:154} INFO - Started process (PID=1197) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:01:36.425+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:01:36.426+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:01:36.425+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:01:39.866+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:01:39.884+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 3.463 seconds
[2022-12-13T00:02:10.123+0000] {processor.py:154} INFO - Started process (PID=1259) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:02:10.124+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:02:10.124+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:02:10.124+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:02:13.434+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:02:13.449+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 3.330 seconds
[2022-12-13T00:02:43.853+0000] {processor.py:154} INFO - Started process (PID=1319) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:02:43.854+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:02:43.855+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:02:43.855+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:02:47.747+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:02:47.764+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 3.918 seconds
[2022-12-13T00:03:18.610+0000] {processor.py:154} INFO - Started process (PID=1380) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:03:18.611+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:03:18.612+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:03:18.612+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:03:23.826+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:03:23.843+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 5.239 seconds
[2022-12-13T00:03:54.677+0000] {processor.py:154} INFO - Started process (PID=1432) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:03:54.677+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:03:54.678+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:03:54.678+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:03:59.198+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:03:59.219+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 4.546 seconds
[2022-12-13T00:04:30.761+0000] {processor.py:154} INFO - Started process (PID=1493) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:04:30.763+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:04:30.766+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:04:30.765+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:04:36.721+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:04:36.738+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 5.986 seconds
[2022-12-13T00:05:07.483+0000] {processor.py:154} INFO - Started process (PID=1559) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:05:07.484+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:05:07.485+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:05:07.485+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:05:14.563+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:05:14.581+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 7.102 seconds
[2022-12-13T00:05:45.052+0000] {processor.py:154} INFO - Started process (PID=1619) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:05:45.054+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:05:45.056+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:05:45.055+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:05:56.679+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:05:56.744+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 11.672 seconds
[2022-12-13T00:06:27.544+0000] {processor.py:154} INFO - Started process (PID=1677) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:06:27.545+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:06:27.545+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:06:27.545+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:06:31.169+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:06:31.187+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 3.647 seconds
[2022-12-13T00:07:01.495+0000] {processor.py:154} INFO - Started process (PID=1738) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:07:01.496+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:07:01.497+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:07:01.496+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:07:05.831+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:07:05.846+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 4.355 seconds
[2022-12-13T00:07:37.562+0000] {processor.py:154} INFO - Started process (PID=1799) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:07:37.564+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:07:37.566+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:07:37.566+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:07:42.141+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:07:42.156+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 4.599 seconds
[2022-12-13T00:08:13.029+0000] {processor.py:154} INFO - Started process (PID=1855) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:08:13.031+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:08:13.032+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:08:13.031+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:08:21.258+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:08:21.300+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 8.276 seconds
[2022-12-13T00:08:51.409+0000] {processor.py:154} INFO - Started process (PID=1918) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:08:51.410+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:08:51.410+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:08:51.410+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:08:54.710+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:08:54.723+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 3.318 seconds
[2022-12-13T00:09:24.900+0000] {processor.py:154} INFO - Started process (PID=1979) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:09:24.901+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:09:24.902+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:09:24.902+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:09:28.495+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:09:28.508+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 3.612 seconds
[2022-12-13T00:10:04.200+0000] {processor.py:154} INFO - Started process (PID=2040) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:10:04.201+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:10:04.203+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:10:04.203+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:10:09.954+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:10:09.971+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 5.779 seconds
[2022-12-13T00:10:40.166+0000] {processor.py:154} INFO - Started process (PID=2093) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:10:40.167+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:10:40.168+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:10:40.168+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:10:44.329+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:10:44.345+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 4.183 seconds
[2022-12-13T00:11:14.741+0000] {processor.py:154} INFO - Started process (PID=2153) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:11:14.742+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:11:14.744+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:11:14.743+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:11:19.630+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:11:19.647+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 4.911 seconds
[2022-12-13T00:11:49.731+0000] {processor.py:154} INFO - Started process (PID=2214) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:11:49.750+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:11:49.753+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:11:49.753+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:11:56.532+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:11:56.575+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 6.854 seconds
[2022-12-13T00:13:00.096+0000] {processor.py:154} INFO - Started process (PID=2347) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:13:00.127+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:13:00.202+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:13:00.202+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:13:30.265+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:13:30.264+0000] {timeout.py:68} ERROR - Process timed out, PID: 2347
[2022-12-13T00:13:30.271+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:13:30.265+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/energy.py
Traceback (most recent call last):
  File "<frozen importlib._bootstrap_external>", line 87, in _path_is_mode_type
  File "<frozen importlib._bootstrap_external>", line 81, in _path_stat
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/.local/lib/python3.7/site-packages/tensorflow/_api/v2/compat/v1/config/experimental/__init__.cpython-37m-x86_64-linux-gnu.so'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/energy.py", line 23, in <module>
    import tensorflow as tf
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/__init__.py", line 51, in <module>
    from ._api.v2 import compat
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/_api/v2/compat/__init__.py", line 37, in <module>
    from . import v1
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/_api/v2/compat/v1/__init__.py", line 30, in <module>
    from . import compat
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/_api/v2/compat/v1/compat/__init__.py", line 37, in <module>
    from . import v1
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/_api/v2/compat/v1/compat/v1/__init__.py", line 31, in <module>
    from tensorflow._api.v2.compat.v1 import config
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/_api/v2/compat/v1/config/__init__.py", line 8, in <module>
    from . import experimental
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 963, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 906, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1280, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1252, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1383, in find_spec
  File "<frozen importlib._bootstrap_external>", line 95, in _path_isfile
  File "<frozen importlib._bootstrap_external>", line 87, in _path_is_mode_type
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/energy.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.2/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.2/best-practices.html#reducing-dag-complexity, PID: 2347
[2022-12-13T00:13:30.272+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:13:30.301+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 30.578 seconds
[2022-12-13T00:14:02.144+0000] {processor.py:154} INFO - Started process (PID=2478) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:14:02.181+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:14:02.192+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:14:02.191+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:14:32.257+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:14:32.256+0000] {timeout.py:68} ERROR - Process timed out, PID: 2478
[2022-12-13T00:14:32.336+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:14:32.275+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/energy.py
Traceback (most recent call last):
  File "<frozen importlib._bootstrap_external>", line 87, in _path_is_mode_type
  File "<frozen importlib._bootstrap_external>", line 81, in _path_stat
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/.local/lib/python3.7/site-packages/tensorflow/_api/v2/compat/v1/experimental/__init__.cpython-37m-x86_64-linux-gnu.so'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/energy.py", line 23, in <module>
    import tensorflow as tf
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/__init__.py", line 51, in <module>
    from ._api.v2 import compat
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/_api/v2/compat/__init__.py", line 37, in <module>
    from . import v1
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/_api/v2/compat/v1/__init__.py", line 30, in <module>
    from . import compat
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/_api/v2/compat/v1/compat/__init__.py", line 37, in <module>
    from . import v1
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/_api/v2/compat/v1/compat/v1/__init__.py", line 38, in <module>
    from tensorflow._api.v2.compat.v1 import experimental
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 963, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 906, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1280, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1252, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1383, in find_spec
  File "<frozen importlib._bootstrap_external>", line 95, in _path_isfile
  File "<frozen importlib._bootstrap_external>", line 87, in _path_is_mode_type
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/energy.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.2/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.2/best-practices.html#reducing-dag-complexity, PID: 2478
[2022-12-13T00:14:32.387+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:14:32.599+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 30.685 seconds
[2022-12-13T00:15:02.913+0000] {processor.py:154} INFO - Started process (PID=2579) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:15:02.913+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:15:02.914+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:15:02.914+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:15:06.494+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:15:06.509+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 3.599 seconds
[2022-12-13T00:15:55.360+0000] {processor.py:154} INFO - Started process (PID=2713) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:15:55.364+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:15:55.378+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:15:55.377+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:16:22.938+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:16:22.954+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 27.623 seconds
[2022-12-13T00:16:53.736+0000] {processor.py:154} INFO - Started process (PID=2812) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:16:53.737+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:16:53.740+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:16:53.739+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:16:58.539+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:16:58.556+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 4.831 seconds
[2022-12-13T00:17:28.728+0000] {processor.py:154} INFO - Started process (PID=2875) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:17:28.729+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:17:28.730+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:17:28.730+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:17:32.756+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:17:32.771+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 4.050 seconds
[2022-12-13T00:18:03.293+0000] {processor.py:154} INFO - Started process (PID=2931) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:18:03.294+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:18:03.295+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:18:03.294+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:18:10.945+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:18:10.987+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 7.700 seconds
[2022-12-13T00:18:41.373+0000] {processor.py:154} INFO - Started process (PID=2995) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:18:41.374+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:18:41.375+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:18:41.374+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:18:45.160+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:18:45.180+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 3.812 seconds
[2022-12-13T00:19:15.492+0000] {processor.py:154} INFO - Started process (PID=3056) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:19:15.493+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:19:15.494+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:19:15.494+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:19:18.961+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:19:18.974+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 3.487 seconds
[2022-12-13T00:19:49.449+0000] {processor.py:154} INFO - Started process (PID=3118) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:19:49.450+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:19:49.451+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:19:49.451+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:19:52.771+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:19:52.786+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 3.341 seconds
[2022-12-13T00:20:23.040+0000] {processor.py:154} INFO - Started process (PID=3171) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:20:23.041+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:20:23.041+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:20:23.041+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:20:28.914+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:20:28.928+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 5.892 seconds
[2022-12-13T00:20:59.312+0000] {processor.py:154} INFO - Started process (PID=3230) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:20:59.316+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:20:59.326+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:20:59.325+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:21:09.990+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:21:10.010+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 10.718 seconds
[2022-12-13T00:21:40.217+0000] {processor.py:154} INFO - Started process (PID=3294) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:21:40.218+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:21:40.219+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:21:40.219+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:21:44.481+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:21:44.515+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 4.304 seconds
[2022-12-13T00:22:14.672+0000] {processor.py:154} INFO - Started process (PID=3355) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:22:14.683+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:22:14.684+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:22:14.684+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:22:17.825+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:22:17.840+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 3.172 seconds
[2022-12-13T00:22:48.055+0000] {processor.py:154} INFO - Started process (PID=3407) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:22:48.056+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:22:48.057+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:22:48.057+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:22:52.536+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:22:52.556+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 4.507 seconds
[2022-12-13T00:23:22.742+0000] {processor.py:154} INFO - Started process (PID=3468) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:23:22.743+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:23:22.743+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:23:22.743+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:23:25.838+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:23:25.851+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 3.112 seconds
[2022-12-13T00:23:56.693+0000] {processor.py:154} INFO - Started process (PID=3529) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:23:56.694+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:23:56.708+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:23:56.707+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:24:02.759+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:24:02.779+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 6.112 seconds
[2022-12-13T00:24:32.904+0000] {processor.py:154} INFO - Started process (PID=3590) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:24:32.905+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:24:32.905+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:24:32.905+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:24:36.853+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:24:36.870+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 3.970 seconds
[2022-12-13T00:25:07.425+0000] {processor.py:154} INFO - Started process (PID=3651) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:25:07.426+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:25:07.427+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:25:07.426+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:25:14.642+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:25:14.655+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 7.236 seconds
[2022-12-13T00:25:44.864+0000] {processor.py:154} INFO - Started process (PID=3703) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:25:44.865+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:25:44.865+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:25:44.865+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:25:48.323+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:25:48.340+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 3.479 seconds
[2022-12-13T00:26:18.411+0000] {processor.py:154} INFO - Started process (PID=3764) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:26:18.423+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:26:18.423+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:26:18.423+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:26:21.557+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:26:21.572+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 3.164 seconds
[2022-12-13T00:26:52.440+0000] {processor.py:154} INFO - Started process (PID=3825) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:26:52.441+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:26:52.442+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:26:52.442+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:26:55.627+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:26:55.640+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 3.204 seconds
[2022-12-13T00:27:25.777+0000] {processor.py:154} INFO - Started process (PID=3886) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:27:25.778+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:27:25.778+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:27:25.778+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:27:29.410+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:27:29.426+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 3.655 seconds
[2022-12-13T00:27:59.619+0000] {processor.py:154} INFO - Started process (PID=3945) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:27:59.620+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:27:59.621+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:27:59.621+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:28:03.100+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:28:03.113+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 3.498 seconds
[2022-12-13T00:28:33.691+0000] {processor.py:154} INFO - Started process (PID=3999) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:28:33.691+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:28:33.692+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:28:33.692+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:28:37.465+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:28:37.481+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 3.793 seconds
[2022-12-13T00:29:08.257+0000] {processor.py:154} INFO - Started process (PID=4060) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:29:08.257+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:29:08.258+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:29:08.258+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:29:11.576+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:29:11.590+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 3.337 seconds
[2022-12-13T00:29:41.921+0000] {processor.py:154} INFO - Started process (PID=4122) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:29:41.921+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:29:41.922+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:29:41.921+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:29:45.018+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:29:45.032+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 3.114 seconds
[2022-12-13T00:30:15.244+0000] {processor.py:154} INFO - Started process (PID=4184) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:30:15.245+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:30:15.246+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:30:15.246+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:30:18.626+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:30:18.638+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 3.402 seconds
[2022-12-13T00:30:49.374+0000] {processor.py:154} INFO - Started process (PID=4236) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:30:49.375+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:30:49.375+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:30:49.375+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:30:53.733+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:30:53.747+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 4.378 seconds
[2022-12-13T00:31:24.679+0000] {processor.py:154} INFO - Started process (PID=4297) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:31:24.681+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:31:24.682+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:31:24.682+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:31:27.969+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:31:27.981+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 3.309 seconds
[2022-12-13T00:31:58.338+0000] {processor.py:154} INFO - Started process (PID=4358) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:31:58.340+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:31:58.342+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:31:58.341+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:32:02.185+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:32:02.197+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 3.863 seconds
[2022-12-13T00:32:32.699+0000] {processor.py:154} INFO - Started process (PID=4419) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:32:32.700+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:32:32.701+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:32:32.701+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:32:36.045+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:32:36.060+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 3.364 seconds
[2022-12-13T00:33:06.195+0000] {processor.py:154} INFO - Started process (PID=4471) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:33:06.196+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:33:06.196+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:33:06.196+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:33:09.752+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:33:09.766+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 3.574 seconds
[2022-12-13T00:33:39.878+0000] {processor.py:154} INFO - Started process (PID=4532) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:33:39.879+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:33:39.879+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:33:39.879+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:33:42.831+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:33:42.845+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 2.970 seconds
[2022-12-13T00:34:13.168+0000] {processor.py:154} INFO - Started process (PID=4593) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:34:13.169+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:34:13.170+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:34:13.170+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:34:16.245+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:34:16.260+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 3.095 seconds
[2022-12-13T00:34:47.045+0000] {processor.py:154} INFO - Started process (PID=4654) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:34:47.056+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:34:47.057+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:34:47.057+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:34:51.022+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:34:51.039+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 4.003 seconds
[2022-12-13T00:35:21.293+0000] {processor.py:154} INFO - Started process (PID=4715) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:35:21.294+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:35:21.295+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:35:21.295+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:35:24.599+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:35:24.617+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 3.328 seconds
[2022-12-13T00:35:54.840+0000] {processor.py:154} INFO - Started process (PID=4774) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:35:54.852+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:35:54.853+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:35:54.853+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:35:58.610+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:35:58.626+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 3.788 seconds
[2022-12-13T00:36:29.203+0000] {processor.py:154} INFO - Started process (PID=4828) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:36:29.204+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:36:29.206+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:36:29.206+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:36:32.570+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:36:32.589+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 3.391 seconds
[2022-12-13T00:37:03.077+0000] {processor.py:154} INFO - Started process (PID=4889) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:37:03.088+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:37:03.088+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:37:03.088+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:37:06.581+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:37:06.597+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 3.523 seconds
[2022-12-13T00:37:37.796+0000] {processor.py:154} INFO - Started process (PID=4948) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:37:37.798+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:37:37.798+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:37:37.798+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:37:41.478+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:37:41.492+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 3.703 seconds
[2022-12-13T00:38:11.850+0000] {processor.py:154} INFO - Started process (PID=5010) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:38:11.861+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:38:11.862+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:38:11.862+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:38:15.616+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:38:15.634+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 3.788 seconds
[2022-12-13T00:38:46.103+0000] {processor.py:154} INFO - Started process (PID=5069) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:38:46.104+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:38:46.105+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:38:46.105+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:38:49.818+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:38:49.830+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 3.732 seconds
[2022-12-13T00:39:21.293+0000] {processor.py:154} INFO - Started process (PID=5123) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:39:21.294+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:39:21.296+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:39:21.295+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:39:25.332+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:39:25.347+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 4.058 seconds
[2022-12-13T00:39:56.665+0000] {processor.py:154} INFO - Started process (PID=5184) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:39:56.667+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:39:56.668+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:39:56.667+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:40:00.757+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:40:00.775+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 4.114 seconds
[2022-12-13T00:40:30.826+0000] {processor.py:154} INFO - Started process (PID=5247) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:40:30.827+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:40:30.829+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:40:30.829+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:40:33.369+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:40:33.382+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 2.560 seconds
[2022-12-13T00:41:03.517+0000] {processor.py:154} INFO - Started process (PID=5308) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:41:03.517+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:41:03.519+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:41:03.518+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:41:06.083+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:41:06.095+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 2.586 seconds
[2022-12-13T00:41:36.202+0000] {processor.py:154} INFO - Started process (PID=5369) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:41:36.212+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:41:36.213+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:41:36.213+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:41:38.524+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:41:38.535+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 2.339 seconds
[2022-12-13T00:42:09.056+0000] {processor.py:154} INFO - Started process (PID=5430) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:42:09.066+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:42:09.067+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:42:09.067+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:42:11.367+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:42:11.378+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 2.327 seconds
[2022-12-13T00:42:41.702+0000] {processor.py:154} INFO - Started process (PID=5491) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:42:41.703+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:42:41.703+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:42:41.703+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:42:43.990+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:42:44.004+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 2.304 seconds
[2022-12-13T00:43:14.199+0000] {processor.py:154} INFO - Started process (PID=5543) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:43:14.199+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:43:14.200+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:43:14.200+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:43:16.687+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:43:16.698+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 2.505 seconds
[2022-12-13T00:43:47.279+0000] {processor.py:154} INFO - Started process (PID=5604) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:43:47.281+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:43:47.282+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:43:47.282+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:43:49.651+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:43:49.663+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 2.391 seconds
[2022-12-13T00:44:19.969+0000] {processor.py:154} INFO - Started process (PID=5665) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:44:19.980+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:44:19.981+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:44:19.981+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:44:22.269+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:44:22.280+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 2.314 seconds
[2022-12-13T00:44:52.712+0000] {processor.py:154} INFO - Started process (PID=5726) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:44:52.712+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:44:52.713+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:44:52.713+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:44:55.026+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:44:55.038+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 2.331 seconds
[2022-12-13T00:45:25.511+0000] {processor.py:154} INFO - Started process (PID=5787) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:45:25.512+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:45:25.512+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:45:25.512+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:45:27.775+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:45:27.787+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 2.273 seconds
[2022-12-13T00:45:58.400+0000] {processor.py:154} INFO - Started process (PID=5848) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:45:58.410+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:45:58.410+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:45:58.410+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:46:00.759+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:46:00.770+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 2.373 seconds
[2022-12-13T00:46:31.148+0000] {processor.py:154} INFO - Started process (PID=5909) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:46:31.158+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:46:31.159+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:46:31.159+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:46:33.429+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:46:33.440+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 2.295 seconds
[2022-12-13T00:47:03.978+0000] {processor.py:154} INFO - Started process (PID=5970) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:47:03.978+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:47:03.979+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:47:03.979+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:47:06.240+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:47:06.251+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 2.277 seconds
[2022-12-13T00:47:37.094+0000] {processor.py:154} INFO - Started process (PID=6031) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:47:37.094+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:47:37.095+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:47:37.095+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:47:39.452+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:47:39.462+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 2.371 seconds
[2022-12-13T00:48:09.830+0000] {processor.py:154} INFO - Started process (PID=6083) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:48:09.831+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:48:09.831+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:48:09.831+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:48:12.230+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:48:12.242+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 2.415 seconds
[2022-12-13T00:48:42.593+0000] {processor.py:154} INFO - Started process (PID=6144) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:48:42.594+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:48:42.595+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:48:42.594+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:48:44.871+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:48:44.883+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 2.293 seconds
[2022-12-13T00:49:15.430+0000] {processor.py:154} INFO - Started process (PID=6205) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:49:15.431+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:49:15.431+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:49:15.431+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:49:17.729+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:49:17.743+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 2.318 seconds
[2022-12-13T00:49:48.099+0000] {processor.py:154} INFO - Started process (PID=6266) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:49:48.099+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:49:48.099+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:49:48.099+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:49:50.379+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:49:50.391+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 2.295 seconds
[2022-12-13T00:50:21.010+0000] {processor.py:154} INFO - Started process (PID=6327) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:50:21.021+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:50:21.021+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:50:21.021+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:50:23.289+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:50:23.364+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 2.359 seconds
[2022-12-13T00:50:53.733+0000] {processor.py:154} INFO - Started process (PID=6388) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:50:53.733+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:50:53.734+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:50:53.734+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:50:56.025+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:50:56.036+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 2.307 seconds
[2022-12-13T00:51:26.633+0000] {processor.py:154} INFO - Started process (PID=6449) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:51:26.634+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:51:26.634+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:51:26.634+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:51:28.854+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:51:28.865+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 2.241 seconds
[2022-12-13T00:51:59.209+0000] {processor.py:154} INFO - Started process (PID=6510) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:51:59.209+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:51:59.210+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:51:59.210+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:52:01.533+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:52:01.546+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 2.340 seconds
[2022-12-13T00:52:31.966+0000] {processor.py:154} INFO - Started process (PID=6568) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:52:31.967+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:52:31.968+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:52:31.967+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:52:34.271+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:52:34.282+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 2.320 seconds
[2022-12-13T00:53:04.777+0000] {processor.py:154} INFO - Started process (PID=6623) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:53:04.788+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:53:04.789+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:53:04.789+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:53:07.143+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:53:07.155+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 2.380 seconds
[2022-12-13T00:53:37.558+0000] {processor.py:154} INFO - Started process (PID=6684) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:53:37.559+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:53:37.559+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:53:37.559+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:53:39.854+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:53:39.866+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 2.311 seconds
[2022-12-13T00:54:10.069+0000] {processor.py:154} INFO - Started process (PID=6745) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:54:10.070+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:54:10.070+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:54:10.070+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:54:12.401+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:54:12.411+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 2.345 seconds
[2022-12-13T00:54:42.645+0000] {processor.py:154} INFO - Started process (PID=6806) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:54:42.646+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:54:42.646+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:54:42.646+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:54:44.933+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:54:44.945+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 2.302 seconds
[2022-12-13T00:55:15.191+0000] {processor.py:154} INFO - Started process (PID=6867) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:55:15.192+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:55:15.192+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:55:15.192+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:55:17.452+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:55:17.463+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 2.275 seconds
[2022-12-13T00:56:45.762+0000] {processor.py:154} INFO - Started process (PID=6942) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:56:45.768+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:56:45.775+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:56:45.773+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:57:15.794+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:57:15.788+0000] {timeout.py:68} ERROR - Process timed out, PID: 6942
[2022-12-13T00:57:15.876+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:57:15.797+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/energy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/energy.py", line 23, in <module>
    import tensorflow as tf
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/__init__.py", line 51, in <module>
    from ._api.v2 import compat
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/_api/v2/compat/__init__.py", line 37, in <module>
    from . import v1
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/_api/v2/compat/v1/__init__.py", line 30, in <module>
    from . import compat
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/_api/v2/compat/v1/compat/__init__.py", line 37, in <module>
    from . import v1
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/_api/v2/compat/v1/compat/v1/__init__.py", line 47, in <module>
    from tensorflow._api.v2.compat.v1 import lite
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/_api/v2/compat/v1/lite/__init__.py", line 9, in <module>
    from . import experimental
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/_api/v2/compat/v1/lite/experimental/__init__.py", line 8, in <module>
    from . import authoring
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/_api/v2/compat/v1/lite/experimental/authoring/__init__.py", line 8, in <module>
    from tensorflow.lite.python.authoring.authoring import compatible
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/lite/python/authoring/authoring.py", line 44, in <module>
    from tensorflow.lite.python import lite
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/lite/python/lite.py", line 30, in <module>
    from tensorflow.lite.experimental.microfrontend.python.ops import audio_microfrontend_op  # pylint: disable=unused-import
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/lite/experimental/microfrontend/python/ops/audio_microfrontend_op.py", line 26, in <module>
    resource_loader.get_path_to_datafile("_audio_microfrontend_op.so"))
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/python/framework/load_library.py", line 70, in load_op_library
    exec(wrappers, module.__dict__)
  File "<string>", line 4, in <module>
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/energy.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.2/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.2/best-practices.html#reducing-dag-complexity, PID: 6942
[2022-12-13T00:57:15.888+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:57:16.107+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 30.393 seconds
[2022-12-13T00:58:38.930+0000] {processor.py:154} INFO - Started process (PID=7025) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:58:38.946+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:58:38.974+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:58:38.971+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T00:59:08.999+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:59:08.992+0000] {timeout.py:68} ERROR - Process timed out, PID: 7025
[2022-12-13T00:59:09.061+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:59:09.004+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/energy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/energy.py", line 23, in <module>
    import tensorflow as tf
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/__init__.py", line 470, in <module>
    _keras._load()
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/python/util/lazy_loader.py", line 41, in _load
    module = importlib.import_module(self.__name__)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/api/__init__.py", line 8, in <module>
    from keras.api import keras
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/api/keras/__init__.py", line 19, in <module>
    from keras.api.keras import datasets
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/api/keras/datasets/__init__.py", line 12, in <module>
    from keras.api.keras.datasets import imdb
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/api/keras/datasets/imdb/__init__.py", line 8, in <module>
    from keras.datasets.imdb import get_word_index
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/datasets/imdb.py", line 21, in <module>
    from keras.preprocessing.sequence import _remove_long_seq
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/preprocessing/__init__.py", line 31, in <module>
    from keras.preprocessing import image
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/preprocessing/image.py", line 48, in <module>
    from scipy import linalg  # noqa: F401
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/linalg/__init__.py", line 195, in <module>
    from .misc import *
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/linalg/misc.py", line 4, in <module>
    from .lapack import get_lapack_funcs
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/linalg/lapack.py", line 818, in <module>
    from scipy.linalg import _flapack
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/energy.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.2/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.2/best-practices.html#reducing-dag-complexity, PID: 7025
[2022-12-13T00:59:09.066+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T00:59:09.228+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 30.375 seconds
[2022-12-13T00:59:55.860+0000] {processor.py:154} INFO - Started process (PID=7098) to work on /opt/airflow/dags/energy.py
[2022-12-13T00:59:55.866+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T00:59:55.878+0000] {logging_mixin.py:120} INFO - [2022-12-13T00:59:55.877+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T01:00:25.892+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:00:25.886+0000] {timeout.py:68} ERROR - Process timed out, PID: 7098
[2022-12-13T01:00:25.940+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:00:25.895+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/energy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/energy.py", line 23, in <module>
    import tensorflow as tf
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/__init__.py", line 470, in <module>
    _keras._load()
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/python/util/lazy_loader.py", line 41, in _load
    module = importlib.import_module(self.__name__)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/api/__init__.py", line 8, in <module>
    from keras.api import keras
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/api/keras/__init__.py", line 19, in <module>
    from keras.api.keras import datasets
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/api/keras/datasets/__init__.py", line 12, in <module>
    from keras.api.keras.datasets import imdb
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/api/keras/datasets/imdb/__init__.py", line 8, in <module>
    from keras.datasets.imdb import get_word_index
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/datasets/imdb.py", line 21, in <module>
    from keras.preprocessing.sequence import _remove_long_seq
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/preprocessing/__init__.py", line 31, in <module>
    from keras.preprocessing import image
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/preprocessing/image.py", line 49, in <module>
    from scipy import ndimage  # noqa: F401
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/ndimage/__init__.py", line 153, in <module>
    from .interpolation import *
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/ndimage/interpolation.py", line 37, in <module>
    from scipy import special
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/special/__init__.py", line 641, in <module>
    from .sf_error import SpecialFunctionWarning, SpecialFunctionError
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 828, in get_code
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/energy.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.2/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.2/best-practices.html#reducing-dag-complexity, PID: 7098
[2022-12-13T01:00:25.944+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T01:00:26.069+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 30.244 seconds
[2022-12-13T01:01:12.894+0000] {processor.py:154} INFO - Started process (PID=7169) to work on /opt/airflow/dags/energy.py
[2022-12-13T01:01:12.899+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T01:01:12.906+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:01:12.904+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T01:01:42.923+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:01:42.916+0000] {timeout.py:68} ERROR - Process timed out, PID: 7169
[2022-12-13T01:01:42.980+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:01:42.928+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/energy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/energy.py", line 24, in <module>
    from sklearn.preprocessing import MinMaxScaler
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 28, in <module>
    from .fixes import np_version, parse_version
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/fixes.py", line 20, in <module>
    import scipy.stats
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/__init__.py", line 441, in <module>
    from .stats import *
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/stats.py", line 37, in <module>
    from scipy.spatial.distance import cdist
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/spatial/__init__.py", line 98, in <module>
    from .qhull import *
  File "qhull.pyx", line 1, in init scipy.spatial.qhull
  File "<frozen importlib._bootstrap>", line 416, in parent
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/energy.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.2/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.2/best-practices.html#reducing-dag-complexity, PID: 7169
[2022-12-13T01:01:42.986+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T01:01:43.194+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 30.335 seconds
[2022-12-13T01:02:25.628+0000] {processor.py:154} INFO - Started process (PID=7239) to work on /opt/airflow/dags/energy.py
[2022-12-13T01:02:25.645+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T01:02:25.652+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:02:25.651+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T01:02:55.715+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:02:55.683+0000] {timeout.py:68} ERROR - Process timed out, PID: 7239
[2022-12-13T01:02:55.936+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:02:55.733+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/energy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/energy.py", line 23, in <module>
    import tensorflow as tf
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/__init__.py", line 470, in <module>
    _keras._load()
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/python/util/lazy_loader.py", line 41, in _load
    module = importlib.import_module(self.__name__)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/__init__.py", line 21, in <module>
    from keras import models
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/models/__init__.py", line 18, in <module>
    from keras.engine.functional import Functional
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/engine/functional.py", line 34, in <module>
    from keras.engine import training as training_lib
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/engine/training.py", line 33, in <module>
    from keras.engine import compile_utils
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/engine/compile_utils.py", line 24, in <module>
    from keras import metrics as metrics_mod
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/metrics/__init__.py", line 33, in <module>
    from keras.metrics.metrics import AUC
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/metrics/metrics.py", line 28, in <module>
    from keras import activations
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/activations.py", line 21, in <module>
    import keras.layers.activation as activation_layers
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/layers/__init__.py", line 211, in <module>
    from keras.layers.rnn.abstract_rnn_cell import AbstractRNNCell
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/layers/rnn/__init__.py", line 66, in <module>
    from keras.layers.rnn.conv_lstm1d import ConvLSTM1D
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/layers/rnn/conv_lstm1d.py", line 18, in <module>
    from keras.layers.rnn.base_conv_lstm import ConvLSTM
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 857, in get_code
  File "<frozen importlib._bootstrap_external>", line 525, in _compile_bytecode
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/energy.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.2/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.2/best-practices.html#reducing-dag-complexity, PID: 7239
[2022-12-13T01:02:55.968+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T01:02:56.446+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 30.879 seconds
[2022-12-13T01:03:48.022+0000] {processor.py:154} INFO - Started process (PID=7310) to work on /opt/airflow/dags/energy.py
[2022-12-13T01:03:48.029+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T01:03:48.035+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:03:48.033+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T01:04:18.043+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:04:18.038+0000] {timeout.py:68} ERROR - Process timed out, PID: 7310
[2022-12-13T01:04:18.081+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:04:18.045+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/energy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/energy.py", line 23, in <module>
    import tensorflow as tf
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/__init__.py", line 470, in <module>
    _keras._load()
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/python/util/lazy_loader.py", line 41, in _load
    module = importlib.import_module(self.__name__)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/api/__init__.py", line 8, in <module>
    from keras.api import keras
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/api/keras/__init__.py", line 19, in <module>
    from keras.api.keras import datasets
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/api/keras/datasets/__init__.py", line 12, in <module>
    from keras.api.keras.datasets import imdb
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/api/keras/datasets/imdb/__init__.py", line 8, in <module>
    from keras.datasets.imdb import get_word_index
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/datasets/imdb.py", line 21, in <module>
    from keras.preprocessing.sequence import _remove_long_seq
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/preprocessing/__init__.py", line 31, in <module>
    from keras.preprocessing import image
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/preprocessing/image.py", line 49, in <module>
    from scipy import ndimage  # noqa: F401
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/ndimage/__init__.py", line 153, in <module>
    from .interpolation import *
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/ndimage/interpolation.py", line 37, in <module>
    from scipy import special
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/special/__init__.py", line 649, in <module>
    from ._logsumexp import logsumexp, softmax, log_softmax
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 854, in get_code
  File "<frozen importlib._bootstrap>", line 224, in _verbose_message
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/energy.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.2/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.2/best-practices.html#reducing-dag-complexity, PID: 7310
[2022-12-13T01:04:18.089+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T01:04:18.244+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 30.293 seconds
[2022-12-13T01:04:57.751+0000] {processor.py:154} INFO - Started process (PID=7373) to work on /opt/airflow/dags/energy.py
[2022-12-13T01:04:57.757+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T01:04:57.763+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:04:57.762+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T01:05:27.778+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:05:27.774+0000] {timeout.py:68} ERROR - Process timed out, PID: 7373
[2022-12-13T01:05:27.807+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:05:27.780+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/energy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/energy.py", line 24, in <module>
    from sklearn.preprocessing import MinMaxScaler
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 25, in <module>
    from . import _joblib
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/_joblib.py", line 7, in <module>
    import joblib
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/__init__.py", line 113, in <module>
    from .memory import Memory, MemorizedResult, register_store_backend
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/memory.py", line 28, in <module>
    from .func_inspect import get_func_code, get_func_name, filter_args
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/func_inspect.py", line 18, in <module>
    from .logger import pformat
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 963, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 898, in _find_spec
  File "<frozen importlib._bootstrap>", line 855, in __enter__
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/energy.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.2/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.2/best-practices.html#reducing-dag-complexity, PID: 7373
[2022-12-13T01:05:27.811+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T01:05:28.014+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 30.330 seconds
[2022-12-13T01:06:15.938+0000] {processor.py:154} INFO - Started process (PID=7445) to work on /opt/airflow/dags/energy.py
[2022-12-13T01:06:15.944+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T01:06:15.950+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:06:15.948+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T01:06:45.973+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:06:45.966+0000] {timeout.py:68} ERROR - Process timed out, PID: 7445
[2022-12-13T01:06:46.051+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:06:45.976+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/energy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/energy.py", line 24, in <module>
    from sklearn.preprocessing import MinMaxScaler
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 28, in <module>
    from .fixes import np_version, parse_version
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/fixes.py", line 20, in <module>
    import scipy.stats
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/__init__.py", line 441, in <module>
    from .stats import *
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/stats.py", line 43, in <module>
    from . import distributions
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/distributions.py", line 8, in <module>
    from ._distn_infrastructure import (rv_discrete, rv_continuous, rv_frozen)
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py", line 24, in <module>
    from scipy import optimize
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/optimize/__init__.py", line 401, in <module>
    from ._minimize import *
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/optimize/_minimize.py", line 27, in <module>
    from ._trustregion_constr import _minimize_trustregion_constr
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/optimize/_trustregion_constr/__init__.py", line 4, in <module>
    from .minimize_trustregion_constr import _minimize_trustregion_constr
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/optimize/_trustregion_constr/minimize_trustregion_constr.py", line 11, in <module>
    from .canonical_constraint import (CanonicalConstraint,
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 857, in get_code
  File "<frozen importlib._bootstrap_external>", line 525, in _compile_bytecode
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/energy.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.2/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.2/best-practices.html#reducing-dag-complexity, PID: 7445
[2022-12-13T01:06:46.061+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T01:06:46.264+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 30.353 seconds
[2022-12-13T01:07:26.306+0000] {processor.py:154} INFO - Started process (PID=7513) to work on /opt/airflow/dags/energy.py
[2022-12-13T01:07:26.324+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T01:07:26.332+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:07:26.331+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T01:07:56.349+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:07:56.336+0000] {timeout.py:68} ERROR - Process timed out, PID: 7513
[2022-12-13T01:07:56.394+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:07:56.356+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/energy.py
Traceback (most recent call last):
  File "<frozen importlib._bootstrap_external>", line 87, in _path_is_mode_type
  File "<frozen importlib._bootstrap_external>", line 81, in _path_stat
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/.local/lib/python3.7/site-packages/tensorflow/_api/v2/compat/v2/strings/__init__.so'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/energy.py", line 23, in <module>
    import tensorflow as tf
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/__init__.py", line 51, in <module>
    from ._api.v2 import compat
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/_api/v2/compat/__init__.py", line 37, in <module>
    from . import v1
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/_api/v2/compat/v1/__init__.py", line 30, in <module>
    from . import compat
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/_api/v2/compat/v1/compat/__init__.py", line 38, in <module>
    from . import v2
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/_api/v2/compat/v1/compat/v2/__init__.py", line 28, in <module>
    from tensorflow._api.v2.compat.v2 import __internal__
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/_api/v2/compat/v2/__init__.py", line 33, in <module>
    from . import compat
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/_api/v2/compat/v2/compat/__init__.py", line 38, in <module>
    from . import v2
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/_api/v2/compat/v2/compat/v2/__init__.py", line 62, in <module>
    from tensorflow._api.v2.compat.v2 import strings
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 963, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 906, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1280, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1252, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1383, in find_spec
  File "<frozen importlib._bootstrap_external>", line 95, in _path_isfile
  File "<frozen importlib._bootstrap_external>", line 87, in _path_is_mode_type
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/energy.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.2/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.2/best-practices.html#reducing-dag-complexity, PID: 7513
[2022-12-13T01:07:56.401+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T01:07:56.696+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 30.438 seconds
[2022-12-13T01:08:55.432+0000] {processor.py:154} INFO - Started process (PID=7583) to work on /opt/airflow/dags/energy.py
[2022-12-13T01:08:55.450+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T01:08:55.458+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:08:55.457+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T01:09:25.472+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:09:25.466+0000] {timeout.py:68} ERROR - Process timed out, PID: 7583
[2022-12-13T01:09:25.535+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:09:25.476+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/energy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/energy.py", line 24, in <module>
    from sklearn.preprocessing import MinMaxScaler
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 28, in <module>
    from .fixes import np_version, parse_version
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/fixes.py", line 20, in <module>
    import scipy.stats
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/__init__.py", line 441, in <module>
    from .stats import *
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/stats.py", line 43, in <module>
    from . import distributions
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/distributions.py", line 10, in <module>
    from . import _continuous_distns
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/_continuous_distns.py", line 22, in <module>
    from . import _stats
  File "_stats.pyx", line 1, in init scipy.stats._stats
  File "<frozen importlib._bootstrap>", line 416, in parent
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/energy.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.2/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.2/best-practices.html#reducing-dag-complexity, PID: 7583
[2022-12-13T01:09:25.543+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T01:09:25.678+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 30.299 seconds
[2022-12-13T01:09:57.509+0000] {processor.py:154} INFO - Started process (PID=7644) to work on /opt/airflow/dags/energy.py
[2022-12-13T01:09:57.518+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T01:09:57.523+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:09:57.522+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T01:10:27.542+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:10:27.535+0000] {timeout.py:68} ERROR - Process timed out, PID: 7644
[2022-12-13T01:10:27.600+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:10:27.544+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/energy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/energy.py", line 23, in <module>
    import tensorflow as tf
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/__init__.py", line 470, in <module>
    _keras._load()
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/python/util/lazy_loader.py", line 41, in _load
    module = importlib.import_module(self.__name__)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/__init__.py", line 21, in <module>
    from keras import models
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/models/__init__.py", line 18, in <module>
    from keras.engine.functional import Functional
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/engine/functional.py", line 34, in <module>
    from keras.engine import training as training_lib
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/engine/training.py", line 33, in <module>
    from keras.engine import compile_utils
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/engine/compile_utils.py", line 24, in <module>
    from keras import metrics as metrics_mod
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/metrics/__init__.py", line 33, in <module>
    from keras.metrics.metrics import AUC
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/metrics/metrics.py", line 28, in <module>
    from keras import activations
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/activations.py", line 21, in <module>
    import keras.layers.activation as activation_layers
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 857, in get_code
  File "<frozen importlib._bootstrap_external>", line 525, in _compile_bytecode
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/energy.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.2/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.2/best-practices.html#reducing-dag-complexity, PID: 7644
[2022-12-13T01:10:27.605+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T01:10:27.772+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 30.292 seconds
[2022-12-13T01:11:23.000+0000] {processor.py:154} INFO - Started process (PID=7714) to work on /opt/airflow/dags/energy.py
[2022-12-13T01:11:23.015+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T01:11:23.020+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:11:23.019+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T01:11:53.039+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:11:53.035+0000] {timeout.py:68} ERROR - Process timed out, PID: 7714
[2022-12-13T01:11:53.052+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:11:53.041+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/energy.py
Traceback (most recent call last):
  File "<frozen importlib._bootstrap_external>", line 87, in _path_is_mode_type
  File "<frozen importlib._bootstrap_external>", line 81, in _path_stat
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/.local/lib/python3.7/site-packages/keras/api/keras/backend/__init__.abi3.so'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/energy.py", line 23, in <module>
    import tensorflow as tf
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/__init__.py", line 470, in <module>
    _keras._load()
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/python/util/lazy_loader.py", line 41, in _load
    module = importlib.import_module(self.__name__)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/api/__init__.py", line 8, in <module>
    from keras.api import keras
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/api/keras/__init__.py", line 16, in <module>
    from keras.api.keras import backend
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 963, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 906, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1280, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1252, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1383, in find_spec
  File "<frozen importlib._bootstrap_external>", line 95, in _path_isfile
  File "<frozen importlib._bootstrap_external>", line 87, in _path_is_mode_type
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/energy.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.2/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.2/best-practices.html#reducing-dag-complexity, PID: 7714
[2022-12-13T01:11:53.058+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T01:11:53.219+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 30.252 seconds
[2022-12-13T01:12:27.262+0000] {processor.py:154} INFO - Started process (PID=7783) to work on /opt/airflow/dags/energy.py
[2022-12-13T01:12:27.284+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T01:12:27.300+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:12:27.299+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T01:12:57.320+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:12:57.310+0000] {timeout.py:68} ERROR - Process timed out, PID: 7783
[2022-12-13T01:12:57.374+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:12:57.324+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/energy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/energy.py", line 23, in <module>
    import tensorflow as tf
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/__init__.py", line 470, in <module>
    _keras._load()
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/python/util/lazy_loader.py", line 41, in _load
    module = importlib.import_module(self.__name__)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/__init__.py", line 21, in <module>
    from keras import models
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/models/__init__.py", line 18, in <module>
    from keras.engine.functional import Functional
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/engine/functional.py", line 34, in <module>
    from keras.engine import training as training_lib
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/engine/training.py", line 33, in <module>
    from keras.engine import compile_utils
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/engine/compile_utils.py", line 24, in <module>
    from keras import metrics as metrics_mod
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/metrics/__init__.py", line 20, in <module>
    from keras.metrics.base_metric import Mean
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 800, in get_code
  File "<frozen importlib._bootstrap_external>", line 407, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 909, in get_filename
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/energy.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.2/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.2/best-practices.html#reducing-dag-complexity, PID: 7783
[2022-12-13T01:12:57.381+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T01:12:57.579+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 30.383 seconds
[2022-12-13T01:13:56.418+0000] {processor.py:154} INFO - Started process (PID=7855) to work on /opt/airflow/dags/energy.py
[2022-12-13T01:13:56.433+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T01:13:56.439+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:13:56.437+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T01:14:26.455+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:14:26.450+0000] {timeout.py:68} ERROR - Process timed out, PID: 7855
[2022-12-13T01:14:26.507+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:14:26.457+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/energy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/energy.py", line 23, in <module>
    import tensorflow as tf
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/__init__.py", line 470, in <module>
    _keras._load()
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/python/util/lazy_loader.py", line 41, in _load
    module = importlib.import_module(self.__name__)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/__init__.py", line 21, in <module>
    from keras import models
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/models/__init__.py", line 18, in <module>
    from keras.engine.functional import Functional
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/engine/functional.py", line 34, in <module>
    from keras.engine import training as training_lib
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/engine/training.py", line 33, in <module>
    from keras.engine import compile_utils
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/engine/compile_utils.py", line 24, in <module>
    from keras import metrics as metrics_mod
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/metrics/__init__.py", line 33, in <module>
    from keras.metrics.metrics import AUC
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/metrics/metrics.py", line 28, in <module>
    from keras import activations
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/activations.py", line 152, in <module>
    @tf.__internal__.dispatch.add_dispatch_support
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py", line 1197, in add_dispatch_support
    return decorator(target)
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py", line 1189, in decorator
    add_type_based_api_dispatcher(op_dispatch_handler)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/energy.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.2/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.2/best-practices.html#reducing-dag-complexity, PID: 7855
[2022-12-13T01:14:26.512+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T01:14:26.651+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 30.262 seconds
[2022-12-13T01:15:22.829+0000] {processor.py:154} INFO - Started process (PID=7935) to work on /opt/airflow/dags/energy.py
[2022-12-13T01:15:22.845+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T01:15:22.855+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:15:22.853+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T01:15:52.869+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:15:52.865+0000] {timeout.py:68} ERROR - Process timed out, PID: 7935
[2022-12-13T01:15:52.904+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:15:52.874+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/energy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/energy.py", line 24, in <module>
    from sklearn.preprocessing import MinMaxScaler
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 28, in <module>
    from .fixes import np_version, parse_version
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/fixes.py", line 20, in <module>
    import scipy.stats
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/__init__.py", line 441, in <module>
    from .stats import *
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/stats.py", line 43, in <module>
    from . import distributions
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/distributions.py", line 10, in <module>
    from . import _continuous_distns
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 857, in get_code
  File "<frozen importlib._bootstrap_external>", line 525, in _compile_bytecode
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/energy.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.2/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.2/best-practices.html#reducing-dag-complexity, PID: 7935
[2022-12-13T01:15:52.908+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T01:15:53.034+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 30.232 seconds
[2022-12-13T01:16:52.817+0000] {processor.py:154} INFO - Started process (PID=8023) to work on /opt/airflow/dags/energy.py
[2022-12-13T01:16:52.832+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T01:16:52.839+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:16:52.837+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T01:17:22.852+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:17:22.846+0000] {timeout.py:68} ERROR - Process timed out, PID: 8023
[2022-12-13T01:17:22.915+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:17:22.856+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/energy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/energy.py", line 24, in <module>
    from sklearn.preprocessing import MinMaxScaler
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 28, in <module>
    from .fixes import np_version, parse_version
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/fixes.py", line 20, in <module>
    import scipy.stats
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/__init__.py", line 441, in <module>
    from .stats import *
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/stats.py", line 43, in <module>
    from . import distributions
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/distributions.py", line 8, in <module>
    from ._distn_infrastructure import (rv_discrete, rv_continuous, rv_frozen)
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py", line 24, in <module>
    from scipy import optimize
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/optimize/__init__.py", line 401, in <module>
    from ._minimize import *
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/optimize/_minimize.py", line 27, in <module>
    from ._trustregion_constr import _minimize_trustregion_constr
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/optimize/_trustregion_constr/__init__.py", line 4, in <module>
    from .minimize_trustregion_constr import _minimize_trustregion_constr
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/optimize/_trustregion_constr/minimize_trustregion_constr.py", line 5, in <module>
    from .._constraints import (
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/optimize/_constraints.py", line 8, in <module>
    from numpy.testing import suppress_warnings
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 963, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 906, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1280, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1252, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1383, in find_spec
  File "<frozen importlib._bootstrap_external>", line 95, in _path_isfile
  File "<frozen importlib._bootstrap_external>", line 87, in _path_is_mode_type
  File "<frozen importlib._bootstrap_external>", line 81, in _path_stat
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/energy.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.2/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.2/best-practices.html#reducing-dag-complexity, PID: 8023
[2022-12-13T01:17:22.922+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T01:17:23.073+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 30.283 seconds
[2022-12-13T01:17:55.375+0000] {processor.py:154} INFO - Started process (PID=8082) to work on /opt/airflow/dags/energy.py
[2022-12-13T01:17:55.380+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T01:17:55.386+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:17:55.385+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T01:18:25.405+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:18:25.398+0000] {timeout.py:68} ERROR - Process timed out, PID: 8082
[2022-12-13T01:18:25.497+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:18:25.410+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/energy.py
Traceback (most recent call last):
  File "<frozen importlib._bootstrap_external>", line 818, in get_code
  File "<frozen importlib._bootstrap_external>", line 916, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.7/concurrent/futures/__pycache__/process.cpython-37.pyc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/energy.py", line 24, in <module>
    from sklearn.preprocessing import MinMaxScaler
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 25, in <module>
    from . import _joblib
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/_joblib.py", line 7, in <module>
    import joblib
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/__init__.py", line 120, in <module>
    from .parallel import Parallel
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/parallel.py", line 26, in <module>
    from ._parallel_backends import (FallbackToBackend, MultiprocessingBackend,
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 17, in <module>
    from .pool import MemmappingPool
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/pool.py", line 31, in <module>
    from ._memmapping_reducer import get_memmapping_reducers
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/_memmapping_reducer.py", line 37, in <module>
    from .externals.loky.backend import resource_tracker
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/externals/loky/__init__.py", line 20, in <module>
    from .reusable_executor import get_reusable_executor
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/externals/loky/reusable_executor.py", line 11, in <module>
    from .process_executor import ProcessPoolExecutor, EXTRA_QUEUED_CALLS
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 77, in <module>
    from concurrent.futures.process import BrokenProcessPool as _BPPException
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 818, in get_code
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/energy.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.2/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.2/best-practices.html#reducing-dag-complexity, PID: 8082
[2022-12-13T01:18:25.521+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T01:18:25.766+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 30.428 seconds
[2022-12-13T01:19:21.087+0000] {processor.py:154} INFO - Started process (PID=8154) to work on /opt/airflow/dags/energy.py
[2022-12-13T01:19:21.102+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T01:19:21.107+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:19:21.106+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T01:19:51.119+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:19:51.113+0000] {timeout.py:68} ERROR - Process timed out, PID: 8154
[2022-12-13T01:19:51.151+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:19:51.122+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/energy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/energy.py", line 24, in <module>
    from sklearn.preprocessing import MinMaxScaler
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 25, in <module>
    from . import _joblib
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/_joblib.py", line 7, in <module>
    import joblib
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/__init__.py", line 120, in <module>
    from .parallel import Parallel
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/parallel.py", line 26, in <module>
    from ._parallel_backends import (FallbackToBackend, MultiprocessingBackend,
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 17, in <module>
    from .pool import MemmappingPool
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/pool.py", line 31, in <module>
    from ._memmapping_reducer import get_memmapping_reducers
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/_memmapping_reducer.py", line 37, in <module>
    from .externals.loky.backend import resource_tracker
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/externals/loky/__init__.py", line 19, in <module>
    from .backend.reduction import set_loky_pickler
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/externals/loky/backend/reduction.py", line 82, in <module>
    from joblib.externals import cloudpickle  # noqa: F401
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/externals/cloudpickle/__init__.py", line 1, in <module>
    from .cloudpickle import *  # noqa
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 812, in get_code
  File "<frozen importlib._bootstrap_external>", line 953, in path_stats
  File "<frozen importlib._bootstrap_external>", line 81, in _path_stat
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/energy.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.2/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.2/best-practices.html#reducing-dag-complexity, PID: 8154
[2022-12-13T01:19:51.156+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T01:19:51.284+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 30.235 seconds
[2022-12-13T01:20:23.249+0000] {processor.py:154} INFO - Started process (PID=8214) to work on /opt/airflow/dags/energy.py
[2022-12-13T01:20:23.253+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T01:20:23.263+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:20:23.261+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T01:20:53.277+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:20:53.271+0000] {timeout.py:68} ERROR - Process timed out, PID: 8214
[2022-12-13T01:20:53.355+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:20:53.280+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/energy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/energy.py", line 24, in <module>
    from sklearn.preprocessing import MinMaxScaler
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 28, in <module>
    from .fixes import np_version, parse_version
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/fixes.py", line 20, in <module>
    import scipy.stats
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/__init__.py", line 441, in <module>
    from .stats import *
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/stats.py", line 43, in <module>
    from . import distributions
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/distributions.py", line 10, in <module>
    from . import _continuous_distns
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 818, in get_code
  File "<frozen importlib._bootstrap_external>", line 917, in get_data
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/energy.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.2/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.2/best-practices.html#reducing-dag-complexity, PID: 8214
[2022-12-13T01:20:53.368+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T01:20:53.551+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 30.340 seconds
[2022-12-13T01:21:48.312+0000] {processor.py:154} INFO - Started process (PID=8293) to work on /opt/airflow/dags/energy.py
[2022-12-13T01:21:48.328+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T01:21:48.335+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:21:48.333+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T01:22:18.342+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:22:18.335+0000] {timeout.py:68} ERROR - Process timed out, PID: 8293
[2022-12-13T01:22:18.405+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:22:18.346+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/energy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/energy.py", line 24, in <module>
    from sklearn.preprocessing import MinMaxScaler
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 28, in <module>
    from .fixes import np_version, parse_version
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/fixes.py", line 20, in <module>
    import scipy.stats
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/__init__.py", line 441, in <module>
    from .stats import *
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/stats.py", line 43, in <module>
    from . import distributions
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/distributions.py", line 8, in <module>
    from ._distn_infrastructure import (rv_discrete, rv_continuous, rv_frozen)
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py", line 24, in <module>
    from scipy import optimize
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/optimize/__init__.py", line 402, in <module>
    from ._root import *
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/optimize/_root.py", line 19, in <module>
    from .minpack import _root_hybr, leastsq
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/optimize/minpack.py", line 13, in <module>
    from ._lsq import least_squares
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/optimize/_lsq/__init__.py", line 3, in <module>
    from .lsq_linear import lsq_linear
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/optimize/_lsq/lsq_linear.py", line 9, in <module>
    from .trf_linear import trf_linear
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/optimize/_lsq/trf_linear.py", line 9, in <module>
    from .givens_elimination import givens_elimination
  File "<frozen importlib._bootstrap>", line 416, in parent
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/energy.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.2/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.2/best-practices.html#reducing-dag-complexity, PID: 8293
[2022-12-13T01:22:18.413+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T01:22:18.563+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 30.299 seconds
[2022-12-13T01:22:52.513+0000] {processor.py:154} INFO - Started process (PID=8353) to work on /opt/airflow/dags/energy.py
[2022-12-13T01:22:52.519+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T01:22:52.526+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:22:52.524+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T01:23:22.557+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:23:22.541+0000] {timeout.py:68} ERROR - Process timed out, PID: 8353
[2022-12-13T01:23:22.800+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:23:22.561+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/energy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/energy.py", line 23, in <module>
    import tensorflow as tf
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/python/__init__.py", line 45, in <module>
    from tensorflow.python.feature_column import feature_column_lib as feature_column
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/python/feature_column/feature_column_lib.py", line 18, in <module>
    from tensorflow.python.feature_column.feature_column import *
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/python/feature_column/feature_column.py", line 143, in <module>
    from tensorflow.python.layers import base
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/python/layers/base.py", line 16, in <module>
    from tensorflow.python.keras.legacy_tf_layers import base
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/python/keras/__init__.py", line 25, in <module>
    from tensorflow.python.keras import models
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/python/keras/models.py", line 20, in <module>
    from tensorflow.python.keras import metrics as metrics_module
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/python/keras/metrics.py", line 34, in <module>
    from tensorflow.python.keras import activations
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/python/keras/activations.py", line 18, in <module>
    from tensorflow.python.keras.layers import advanced_activations
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/python/keras/layers/__init__.py", line 68, in <module>
    from tensorflow.python.keras.layers.core import Masking
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/python/keras/layers/core.py", line 54, in <module>
    from tensorflow.python.ops import standard_ops
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/python/ops/standard_ops.py", line 75, in <module>
    from tensorflow.python.ops.ragged import ragged_dispatch as _ragged_dispatch
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/python/ops/ragged/ragged_dispatch.py", line 28, in <module>
    @dispatch.dispatch_for_unary_elementwise_apis(ragged_tensor.Ragged)
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py", line 787, in decorator
    _add_dispatch_for_unary_elementwise_api(api, x_type, handler)
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py", line 980, in _add_dispatch_for_unary_elementwise_api
    @dispatch_for_api(api, {x_name: x_type})
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py", line 350, in decorator
    dispatch_target = _add_name_scope_wrapper(dispatch_target, api_signature)
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py", line 443, in _add_name_scope_wrapper
    func_argspec = tf_inspect.getargspec(func)
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/python/util/tf_inspect.py", line 140, in getargspec
    return _getargspec(target)
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/python/util/tf_inspect.py", line 81, in _getargspec
    fullargspecs = getfullargspec(target)
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/python/util/tf_inspect.py", line 266, in getfullargspec
    return _getfullargspec(target)
  File "/usr/local/lib/python3.7/inspect.py", line 1177, in getfullargspec
    kwonlyargs, kwdefaults, annotations)
  File "<string>", line 1, in __new__
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/energy.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.2/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.2/best-practices.html#reducing-dag-complexity, PID: 8353
[2022-12-13T01:23:22.833+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T01:23:23.582+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 31.093 seconds
[2022-12-13T01:24:11.984+0000] {processor.py:154} INFO - Started process (PID=8414) to work on /opt/airflow/dags/energy.py
[2022-12-13T01:24:11.992+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T01:24:12.001+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:24:11.999+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T01:24:42.019+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:24:42.012+0000] {timeout.py:68} ERROR - Process timed out, PID: 8414
[2022-12-13T01:24:42.065+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:24:42.023+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/energy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/energy.py", line 23, in <module>
    import tensorflow as tf
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/__init__.py", line 51, in <module>
    from ._api.v2 import compat
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/_api/v2/compat/__init__.py", line 37, in <module>
    from . import v1
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/_api/v2/compat/v1/__init__.py", line 30, in <module>
    from . import compat
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/_api/v2/compat/v1/compat/__init__.py", line 38, in <module>
    from . import v2
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/_api/v2/compat/v1/compat/v2/__init__.py", line 28, in <module>
    from tensorflow._api.v2.compat.v2 import __internal__
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/_api/v2/compat/v2/__init__.py", line 33, in <module>
    from . import compat
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/_api/v2/compat/v2/compat/__init__.py", line 38, in <module>
    from . import v2
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/_api/v2/compat/v2/compat/v2/__init__.py", line 40, in <module>
    from tensorflow._api.v2.compat.v2 import experimental
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/_api/v2/compat/v2/experimental/__init__.py", line 9, in <module>
    from . import dtensor
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/_api/v2/compat/v2/experimental/dtensor/__init__.py", line 34, in <module>
    from tensorflow.dtensor.python.input_util import DTensorDataset
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/dtensor/python/input_util.py", line 82, in <module>
    @dataclasses.dataclass
  File "/usr/local/lib/python3.7/dataclasses.py", line 1010, in dataclass
    return wrap(_cls)
  File "/usr/local/lib/python3.7/dataclasses.py", line 1002, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash, frozen)
  File "/usr/local/lib/python3.7/dataclasses.py", line 921, in _process_class
    globals,
  File "/usr/local/lib/python3.7/dataclasses.py", line 523, in _init_fn
    return_type=None)
  File "/usr/local/lib/python3.7/dataclasses.py", line 387, in _create_fn
    exec(txt, globals, ns)
  File "<string>", line 1, in <module>
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/energy.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.2/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.2/best-practices.html#reducing-dag-complexity, PID: 8414
[2022-12-13T01:24:42.069+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T01:24:42.196+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 30.253 seconds
[2022-12-13T01:25:29.067+0000] {processor.py:154} INFO - Started process (PID=8484) to work on /opt/airflow/dags/energy.py
[2022-12-13T01:25:29.085+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T01:25:29.101+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:25:29.098+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T01:25:58.995+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:25:58.984+0000] {timeout.py:68} ERROR - Process timed out, PID: 8484
[2022-12-13T01:25:59.032+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:25:58.999+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/energy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/energy.py", line 23, in <module>
    import tensorflow as tf
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/__init__.py", line 470, in <module>
    _keras._load()
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/python/util/lazy_loader.py", line 41, in _load
    module = importlib.import_module(self.__name__)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/api/__init__.py", line 8, in <module>
    from keras.api import keras
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/api/keras/__init__.py", line 19, in <module>
    from keras.api.keras import datasets
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/api/keras/datasets/__init__.py", line 12, in <module>
    from keras.api.keras.datasets import imdb
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/api/keras/datasets/imdb/__init__.py", line 8, in <module>
    from keras.datasets.imdb import get_word_index
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/datasets/imdb.py", line 21, in <module>
    from keras.preprocessing.sequence import _remove_long_seq
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/preprocessing/__init__.py", line 31, in <module>
    from keras.preprocessing import image
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/preprocessing/image.py", line 48, in <module>
    from scipy import linalg  # noqa: F401
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/linalg/__init__.py", line 195, in <module>
    from .misc import *
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/linalg/misc.py", line 4, in <module>
    from .lapack import get_lapack_funcs
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/linalg/lapack.py", line 888, in <module>
    routine.__doc__ = p1.sub(backtickrepl, routine.__doc__)
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/linalg/lapack.py", line 876, in backtickrepl
    def backtickrepl(m):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/energy.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.2/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.2/best-practices.html#reducing-dag-complexity, PID: 8484
[2022-12-13T01:25:59.039+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T01:25:59.252+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 30.358 seconds
[2022-12-13T01:26:44.729+0000] {processor.py:154} INFO - Started process (PID=8548) to work on /opt/airflow/dags/energy.py
[2022-12-13T01:26:44.746+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T01:26:44.763+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:26:44.761+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T01:27:14.777+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:27:14.772+0000] {timeout.py:68} ERROR - Process timed out, PID: 8548
[2022-12-13T01:27:14.790+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:27:14.778+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/energy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/energy.py", line 23, in <module>
    import tensorflow as tf
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/__init__.py", line 470, in <module>
    _keras._load()
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/python/util/lazy_loader.py", line 41, in _load
    module = importlib.import_module(self.__name__)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/api/_v2/__init__.py", line 8, in <module>
    from keras.api._v2 import keras
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/api/_v2/keras/__init__.py", line 15, in <module>
    from keras.api._v2.keras import applications
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/api/_v2/keras/applications/__init__.py", line 22, in <module>
    from keras.api._v2.keras.applications import resnet_rs
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 963, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 906, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1280, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1252, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1364, in find_spec
  File "<frozen importlib._bootstrap_external>", line 81, in _path_stat
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/energy.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.2/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.2/best-practices.html#reducing-dag-complexity, PID: 8548
[2022-12-13T01:27:14.793+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T01:27:14.930+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 30.247 seconds
[2022-12-13T01:27:58.683+0000] {processor.py:154} INFO - Started process (PID=8618) to work on /opt/airflow/dags/energy.py
[2022-12-13T01:27:58.698+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T01:27:58.704+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:27:58.703+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T01:28:28.725+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:28:28.719+0000] {timeout.py:68} ERROR - Process timed out, PID: 8618
[2022-12-13T01:28:28.760+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:28:28.728+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/energy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/energy.py", line 23, in <module>
    import tensorflow as tf
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/__init__.py", line 470, in <module>
    _keras._load()
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/python/util/lazy_loader.py", line 41, in _load
    module = importlib.import_module(self.__name__)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/api/__init__.py", line 8, in <module>
    from keras.api import keras
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/api/keras/__init__.py", line 13, in <module>
    from keras.api.keras import __internal__
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/api/keras/__internal__/__init__.py", line 9, in <module>
    from keras.api.keras.__internal__ import legacy
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/api/keras/__internal__/legacy/__init__.py", line 8, in <module>
    from keras.api.keras.__internal__.legacy import layers
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/api/keras/__internal__/legacy/layers/__init__.py", line 25, in <module>
    from keras.legacy_tf_layers.core import Dense
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 963, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 882, in _find_spec
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/energy.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.2/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.2/best-practices.html#reducing-dag-complexity, PID: 8618
[2022-12-13T01:28:28.763+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T01:28:28.964+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 30.301 seconds
[2022-12-13T01:29:14.085+0000] {processor.py:154} INFO - Started process (PID=8688) to work on /opt/airflow/dags/energy.py
[2022-12-13T01:29:14.101+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T01:29:14.110+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:29:14.108+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T01:29:44.126+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:29:44.121+0000] {timeout.py:68} ERROR - Process timed out, PID: 8688
[2022-12-13T01:29:44.171+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:29:44.128+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/energy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/energy.py", line 24, in <module>
    from sklearn.preprocessing import MinMaxScaler
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 28, in <module>
    from .fixes import np_version, parse_version
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/fixes.py", line 20, in <module>
    import scipy.stats
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/__init__.py", line 441, in <module>
    from .stats import *
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/stats.py", line 37, in <module>
    from scipy.spatial.distance import cdist
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/spatial/__init__.py", line 102, in <module>
    from ._geometric_slerp import geometric_slerp
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/spatial/_geometric_slerp.py", line 8, in <module>
    from scipy.spatial.distance import euclidean
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/spatial/distance.py", line 121, in <module>
    from . import _distance_wrap
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 963, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 906, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1280, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1252, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1394, in find_spec
  File "<frozen importlib._bootstrap_external>", line 95, in _path_isfile
  File "<frozen importlib._bootstrap_external>", line 87, in _path_is_mode_type
  File "<frozen importlib._bootstrap_external>", line 81, in _path_stat
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/energy.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.2/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.2/best-practices.html#reducing-dag-complexity, PID: 8688
[2022-12-13T01:29:44.179+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T01:29:44.375+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 30.330 seconds
[2022-12-13T01:30:32.626+0000] {processor.py:154} INFO - Started process (PID=8756) to work on /opt/airflow/dags/energy.py
[2022-12-13T01:30:32.632+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T01:30:32.638+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:30:32.637+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T01:31:02.658+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:31:02.649+0000] {timeout.py:68} ERROR - Process timed out, PID: 8756
[2022-12-13T01:31:02.730+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:31:02.662+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/energy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/energy.py", line 23, in <module>
    import tensorflow as tf
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/__init__.py", line 470, in <module>
    _keras._load()
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/python/util/lazy_loader.py", line 41, in _load
    module = importlib.import_module(self.__name__)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/__init__.py", line 21, in <module>
    from keras import models
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/models/__init__.py", line 18, in <module>
    from keras.engine.functional import Functional
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/engine/functional.py", line 26, in <module>
    from keras import backend
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/backend.py", line 34, in <module>
    from keras.engine import keras_tensor
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/engine/keras_tensor.py", line 19, in <module>
    from keras.utils import object_identity
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/utils/__init__.py", line 55, in <module>
    from keras.utils.sidecar_evaluator import SidecarEvaluator
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/utils/sidecar_evaluator.py", line 22, in <module>
    from keras.optimizers.optimizer_experimental import (
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/optimizers/__init__.py", line 39, in <module>
    from keras.optimizers.optimizer_experimental import (
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 963, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 906, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1280, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1252, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1392, in find_spec
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/energy.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.2/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.2/best-practices.html#reducing-dag-complexity, PID: 8756
[2022-12-13T01:31:02.742+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T01:31:02.983+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 30.400 seconds
[2022-12-13T01:31:44.938+0000] {processor.py:154} INFO - Started process (PID=8819) to work on /opt/airflow/dags/energy.py
[2022-12-13T01:31:44.943+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T01:31:44.949+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:31:44.948+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T01:32:14.986+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:32:14.980+0000] {timeout.py:68} ERROR - Process timed out, PID: 8819
[2022-12-13T01:32:15.119+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:32:14.998+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/energy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/energy.py", line 23, in <module>
    import tensorflow as tf
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/__init__.py", line 470, in <module>
    _keras._load()
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/python/util/lazy_loader.py", line 41, in _load
    module = importlib.import_module(self.__name__)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/__init__.py", line 21, in <module>
    from keras import models
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/models/__init__.py", line 18, in <module>
    from keras.engine.functional import Functional
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/engine/functional.py", line 34, in <module>
    from keras.engine import training as training_lib
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/engine/training.py", line 33, in <module>
    from keras.engine import compile_utils
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/engine/compile_utils.py", line 24, in <module>
    from keras import metrics as metrics_mod
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/metrics/__init__.py", line 33, in <module>
    from keras.metrics.metrics import AUC
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/metrics/metrics.py", line 28, in <module>
    from keras import activations
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/activations.py", line 21, in <module>
    import keras.layers.activation as activation_layers
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/layers/__init__.py", line 42, in <module>
    from keras.layers.convolutional.conv1d import Conv1D
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/layers/convolutional/__init__.py", line 22, in <module>
    from keras.layers.convolutional.conv1d_transpose import Conv1DTranspose
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/layers/convolutional/conv1d_transpose.py", line 36, in <module>
    class Conv1DTranspose(Conv1D):
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/layers/convolutional/conv1d_transpose.py", line 141, in Conv1DTranspose
    bias_constraint=None,
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/dtensor/utils.py", line 41, in allow_initializer_layout
    def allow_initializer_layout(init_method):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/energy.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.2/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.2/best-practices.html#reducing-dag-complexity, PID: 8819
[2022-12-13T01:32:15.127+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T01:32:15.321+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 30.421 seconds
[2022-12-13T01:33:02.866+0000] {processor.py:154} INFO - Started process (PID=8889) to work on /opt/airflow/dags/energy.py
[2022-12-13T01:33:02.883+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T01:33:02.896+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:33:02.895+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T01:33:32.920+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:33:32.916+0000] {timeout.py:68} ERROR - Process timed out, PID: 8889
[2022-12-13T01:33:32.932+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:33:32.922+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/energy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/energy.py", line 23, in <module>
    import tensorflow as tf
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/__init__.py", line 470, in <module>
    _keras._load()
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/python/util/lazy_loader.py", line 41, in _load
    module = importlib.import_module(self.__name__)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/api/_v2/__init__.py", line 8, in <module>
    from keras.api._v2 import keras
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/api/_v2/keras/__init__.py", line 24, in <module>
    from keras.api._v2.keras import layers
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 857, in get_code
  File "<frozen importlib._bootstrap_external>", line 525, in _compile_bytecode
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/energy.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.2/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.2/best-practices.html#reducing-dag-complexity, PID: 8889
[2022-12-13T01:33:32.935+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T01:33:33.079+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 30.246 seconds
[2022-12-13T01:34:15.516+0000] {processor.py:154} INFO - Started process (PID=8960) to work on /opt/airflow/dags/energy.py
[2022-12-13T01:34:15.532+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T01:34:15.539+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:34:15.537+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T01:34:45.554+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:34:45.550+0000] {timeout.py:68} ERROR - Process timed out, PID: 8960
[2022-12-13T01:34:45.568+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:34:45.555+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/energy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/energy.py", line 24, in <module>
    from sklearn.preprocessing import MinMaxScaler
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 26, in <module>
    from ..exceptions import DataConversionWarning
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 327, in __exit__
  File "<frozen importlib._bootstrap>", line 224, in _verbose_message
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/energy.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.2/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.2/best-practices.html#reducing-dag-complexity, PID: 8960
[2022-12-13T01:34:45.571+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T01:34:45.731+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 30.247 seconds
[2022-12-13T01:35:32.505+0000] {processor.py:154} INFO - Started process (PID=9029) to work on /opt/airflow/dags/energy.py
[2022-12-13T01:35:32.522+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T01:35:32.531+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:35:32.529+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T01:36:02.546+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:36:02.542+0000] {timeout.py:68} ERROR - Process timed out, PID: 9029
[2022-12-13T01:36:02.612+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:36:02.548+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/energy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/energy.py", line 24, in <module>
    from sklearn.preprocessing import MinMaxScaler
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 28, in <module>
    from .fixes import np_version, parse_version
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/fixes.py", line 20, in <module>
    import scipy.stats
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/__init__.py", line 441, in <module>
    from .stats import *
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/stats.py", line 43, in <module>
    from . import distributions
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/distributions.py", line 10, in <module>
    from . import _continuous_distns
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/_continuous_distns.py", line 22, in <module>
    from . import _stats
  File "_stats.pyx", line 1, in init scipy.stats._stats
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/energy.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.2/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.2/best-practices.html#reducing-dag-complexity, PID: 9029
[2022-12-13T01:36:02.625+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T01:36:02.791+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 30.334 seconds
[2022-12-13T01:36:45.441+0000] {processor.py:154} INFO - Started process (PID=9093) to work on /opt/airflow/dags/energy.py
[2022-12-13T01:36:45.457+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T01:36:45.467+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:36:45.465+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T01:37:15.487+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:37:15.480+0000] {timeout.py:68} ERROR - Process timed out, PID: 9093
[2022-12-13T01:37:15.572+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:37:15.494+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/energy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/energy.py", line 23, in <module>
    import tensorflow as tf
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/__init__.py", line 51, in <module>
    from ._api.v2 import compat
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/_api/v2/compat/__init__.py", line 37, in <module>
    from . import v1
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/_api/v2/compat/v1/__init__.py", line 30, in <module>
    from . import compat
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/_api/v2/compat/v1/compat/__init__.py", line 38, in <module>
    from . import v2
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/_api/v2/compat/v1/compat/v2/__init__.py", line 28, in <module>
    from tensorflow._api.v2.compat.v2 import __internal__
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/_api/v2/compat/v2/__init__.py", line 33, in <module>
    from . import compat
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/_api/v2/compat/v2/compat/__init__.py", line 38, in <module>
    from . import v2
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/_api/v2/compat/v2/compat/v2/__init__.py", line 329, in <module>
    from tensorboard.summary._tf import summary
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorboard/summary/__init__.py", line 22, in <module>
    from tensorboard.summary import v1  # noqa: F401
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorboard/summary/v1.py", line 23, in <module>
    from tensorboard.plugins.histogram import summary as _histogram_summary
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorboard/plugins/histogram/summary.py", line 35, in <module>
    from tensorboard.plugins.histogram import summary_v2
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorboard/plugins/histogram/summary_v2.py", line 35, in <module>
    from tensorboard.util import tensor_util
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorboard/util/tensor_util.py", line 20, in <module>
    from tensorboard.compat.tensorflow_stub import dtypes, compat, tensor_shape
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/__init__.py", line 22, in <module>
    from .dtypes import as_dtype  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py", line 19, in <module>
    from . import pywrap_tensorflow
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/pywrap_tensorflow.py", line 22, in <module>
    from .io import gfile
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/io/__init__.py", line 17, in <module>
    from . import gfile  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/io/gfile.py", line 33, in <module>
    import boto3
  File "/home/airflow/.local/lib/python3.7/site-packages/boto3/__init__.py", line 17, in <module>
    from boto3.session import Session
  File "/home/airflow/.local/lib/python3.7/site-packages/boto3/session.py", line 17, in <module>
    import botocore.session
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/session.py", line 30, in <module>
    from botocore import (
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/handlers.py", line 94, in <module>
    VERSION_ID_SUFFIX = re.compile(r'\?versionId=[^\s]+$')
  File "/usr/local/lib/python3.7/re.py", line 236, in compile
    return _compile(pattern, flags)
  File "/usr/local/lib/python3.7/re.py", line 288, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/local/lib/python3.7/sre_compile.py", line 768, in compile
    code = _code(p, flags)
  File "/usr/local/lib/python3.7/sre_compile.py", line 607, in _code
    _compile(code, p.data, flags)
  File "/usr/local/lib/python3.7/sre_compile.py", line 148, in _compile
    _compile(code, av[2], flags)
  File "/usr/local/lib/python3.7/sre_compile.py", line 90, in _compile
    for op, av in pattern:
  File "/usr/local/lib/python3.7/sre_parse.py", line 164, in __getitem__
    def __getitem__(self, index):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/energy.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.2/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.2/best-practices.html#reducing-dag-complexity, PID: 9093
[2022-12-13T01:37:15.579+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T01:37:15.723+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 30.326 seconds
[2022-12-13T01:38:04.850+0000] {processor.py:154} INFO - Started process (PID=9165) to work on /opt/airflow/dags/energy.py
[2022-12-13T01:38:04.859+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T01:38:04.865+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:38:04.864+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T01:38:34.892+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:38:34.877+0000] {timeout.py:68} ERROR - Process timed out, PID: 9165
[2022-12-13T01:38:34.955+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:38:34.899+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/energy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/energy.py", line 24, in <module>
    from sklearn.preprocessing import MinMaxScaler
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 28, in <module>
    from .fixes import np_version, parse_version
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/fixes.py", line 20, in <module>
    import scipy.stats
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/__init__.py", line 441, in <module>
    from .stats import *
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/stats.py", line 37, in <module>
    from scipy.spatial.distance import cdist
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/spatial/__init__.py", line 102, in <module>
    from ._geometric_slerp import geometric_slerp
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/spatial/_geometric_slerp.py", line 8, in <module>
    from scipy.spatial.distance import euclidean
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/spatial/distance.py", line 1904, in <module>
    pdist_func=PDistMetricWrapper('seuclidean'),
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/energy.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.2/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.2/best-practices.html#reducing-dag-complexity, PID: 9165
[2022-12-13T01:38:34.961+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T01:38:35.151+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 30.335 seconds
[2022-12-13T01:39:13.022+0000] {processor.py:154} INFO - Started process (PID=9231) to work on /opt/airflow/dags/energy.py
[2022-12-13T01:39:13.027+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/energy.py for tasks to queue
[2022-12-13T01:39:13.035+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:39:13.033+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/energy.py
[2022-12-13T01:39:43.052+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:39:43.039+0000] {timeout.py:68} ERROR - Process timed out, PID: 9231
[2022-12-13T01:39:43.088+0000] {logging_mixin.py:120} INFO - [2022-12-13T01:39:43.059+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/energy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/energy.py", line 23, in <module>
    import tensorflow as tf
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/__init__.py", line 470, in <module>
    _keras._load()
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/python/util/lazy_loader.py", line 41, in _load
    module = importlib.import_module(self.__name__)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/api/_v2/__init__.py", line 8, in <module>
    from keras.api._v2 import keras
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/api/_v2/keras/__init__.py", line 15, in <module>
    from keras.api._v2.keras import applications
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/api/_v2/keras/applications/__init__.py", line 22, in <module>
    from keras.api._v2.keras.applications import resnet_rs
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 963, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 906, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1280, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1252, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1379, in find_spec
  File "<frozen importlib._bootstrap_external>", line 59, in _path_join
  File "<frozen importlib._bootstrap_external>", line 59, in <listcomp>
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/energy.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.2/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.2/best-practices.html#reducing-dag-complexity, PID: 9231
[2022-12-13T01:39:43.093+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/energy.py
[2022-12-13T01:39:43.232+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/energy.py took 30.249 seconds
